### ISSUE TITLE
Reduce notifications?

### ISSUE THREAD

**Issue by karlvr** [franmastromarino/vs-code-settings-os#3]
I get a notification when I open a project that has `settings.${os}.json` files that the extension has done something, and I get a notification on projects that _don't_ use it that it hasn't managed to do anything... I have to dismiss that manually. I think notifications are probably not necessary... just a little output in the Output channel?

Maybe if a `settings.json` exists and no `settings.${os}.json` or `settings.all.json` files exists you can just assume that this project doesn't use the extension and be silent?

**Comment by franmastromarino** [comment]
Hello @karlvr,
Thank you for taking the time to write to me. I agree with all your recommendations, however, currently, I don't have time to implement these improvements. Feel free to fork and make a PR, and I'll review it.

**Comment by karlvr** [comment]
Good things take time :-)
